using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using StonyGrey.ObjectMapper.Configuration;
using StonyGrey.ObjectMapper.Extensions;

using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

using Targets = System.Collections.Immutable.ImmutableArray<(Microsoft.CodeAnalysis.SyntaxNode node, Microsoft.CodeAnalysis.INamedTypeSymbol source, Microsoft.CodeAnalysis.INamedTypeSymbol destination, StonyGrey.ObjectMapper.MappingContext context)?>;

namespace StonyGrey.ObjectMapper;
internal sealed class MappingBuilder : IDisposable
{
    private readonly Targets _targets;
    private readonly INamedTypeSymbol _source;
    private readonly INamedTypeSymbol _destination;
    private readonly ImmutableArray<IPropertySymbol> _destinationProperties;
    private readonly MappingContext _mappingContext;
    private readonly Compilation _compilation;
    private readonly ConfigurationValues _configurationValues;
    private readonly StringWriter _writer = new();
    private readonly IndentedTextWriter _indentWriter;

    public SourceText Text { get; private set; }

    public MappingBuilder(INamedTypeSymbol source, INamedTypeSymbol destination, ImmutableArray<IPropertySymbol> destinationProperties,
        MappingContext mappingContext, Compilation compilation, ConfigurationValues configurationValues, Targets targets)
    {
        _source = source;
        _destination = destination;
        _destinationProperties = destinationProperties;
        _mappingContext = mappingContext;
        _compilation = compilation;
        _configurationValues = configurationValues;
        _targets = targets;

        _indentWriter = new(_writer, _configurationValues.IndentStyle == IndentStyle.Tab ? "\t" : new string(' ', (int)_configurationValues.IndentSize));

        Text = Build();
    }

    private SourceText Build()
    {
        NamespaceGatherer? namespaces = new();
        var emittedNamespace = false;

        if (_mappingContext.ContainingNamespaceKind != ContainingNamespaceKind.Global)
        {
            if (_mappingContext.ContainingNamespaceKind == ContainingNamespaceKind.Source)
            {
                if (_source.ContainingNamespace.IsGlobalNamespace ||
                    !_source.ContainingNamespace.Contains(_destination.ContainingNamespace))
                {
                    namespaces.Add(_destination.ContainingNamespace);
                }

                if (!_source.ContainingNamespace.IsGlobalNamespace)
                {
                    StartBlock($"namespace {_source.ContainingNamespace.ToDisplayString()}");
                    emittedNamespace = true;
                }
            }
            else if (_mappingContext.ContainingNamespaceKind == ContainingNamespaceKind.Destination)
            {
                if (_destination.ContainingNamespace.IsGlobalNamespace ||
                    !_destination.ContainingNamespace.Contains(_source.ContainingNamespace))
                {
                    namespaces.Add(_source.ContainingNamespace);
                }

                if (!_destination.ContainingNamespace.IsGlobalNamespace)
                {
                    StartBlock($"namespace {_destination.ContainingNamespace.ToDisplayString()}");
                    emittedNamespace = true;
                }
            }
        }
        else
        {
            namespaces.Add(_source.ContainingNamespace);
            namespaces.Add(_destination.ContainingNamespace);
        }

        BuildType(namespaces);

        if (emittedNamespace)
        {
            EndBlock();
        }

        WriteIndentedLine("");

        var append = $"{Environment.NewLine}#nullable enable{Environment.NewLine}";

        var code = namespaces.Values.Count > 0 ?
            string.Join(Environment.NewLine,
                string.Join(Environment.NewLine, namespaces.Values.Select(_ => $"using {_};")),
                string.Empty, append, string.Empty, _writer.ToString()) :
            string.Join(Environment.NewLine, append, string.Empty, _writer.ToString());

        var name = Assembly.GetExecutingAssembly().GetName();
        code = $"// Generated by {name.Name} v{name.Version} at {DateTime.Now}{Environment.NewLine}{Environment.NewLine}{code}";

        var sourceText = SourceText.From(code, Encoding.UTF8);

        Debug.WriteLine(sourceText);

        return sourceText;
    }

    private void BuildType(NamespaceGatherer namespaces)
    {
        StartBlock($"public static partial class MappingExtensions");

        var constructors = _destination.Constructors.Where(_ => _.DeclaredAccessibility == Accessibility.Public ||
            (_destination.ContainingAssembly.ExposesInternalsTo(_compilation.Assembly) && _.DeclaredAccessibility == Accessibility.Friend)).ToArray();

        var imessage = _compilation.GetTypeByMetadataName("Google.Protobuf.IMessage");
        var isProtobufSource = imessage != null && _compilation.ClassifyCommonConversion(_source, imessage).IsImplicit;
        var isProtobufTarget = imessage != null && _compilation.ClassifyCommonConversion(_destination, imessage).IsImplicit;

        for (var i = 0; i < constructors.Length; i++)
        {
            var constructor = constructors[i];

            if (!isProtobufSource && isProtobufTarget)
            {
                if (constructor.Parameters.Length == 0)
                {
                    BuildMapToProtobufExtensionMethod(constructor, namespaces);
                }
            }
            else if (isProtobufSource && !isProtobufTarget)
            {
                BuildMapFromProtobufExtensionMethod(namespaces, constructor);
            }
            else
            {
                BuildMapExtensionMethod(namespaces, constructor);
            }

            if (i < constructors.Length - 1)
            {
                WriteIndentedLine();
            }
        }

        if (isProtobufSource && !isProtobufTarget)
        {
            BuildMapFromProtobufExtensionMethod(namespaces);
        }
        else if (!isProtobufSource && !isProtobufTarget)
        {
            BuildMapExtensionMethod(namespaces);
        }

        EndBlock();
    }

    private void BuildMapExtensionMethod(NamespaceGatherer namespaces, IMethodSymbol? constructor = null)
    {
        var fullyQualifiedSource = _source.FullyQualifiedName();
        var fullyQualifiedDestination = _destination.FullyQualifiedName();

        if (constructor == null)
        {
            StartBlock($"public static {fullyQualifiedDestination} Map{(_mappingContext.LongName ? ($"To{_destination.Name}") : string.Empty)}(this {fullyQualifiedSource} self, {fullyQualifiedDestination} target)");
        }
        else
        {
            var parameters = new string[constructor.Parameters.Length + 1];
            parameters[0] = $"this {fullyQualifiedSource} self";

            for (var i = 0; i < constructor.Parameters.Length; i++)
            {
                var parameter = constructor.Parameters[i];
                namespaces.Add(parameter.Type.ContainingNamespace);
                var nullableAnnotation = parameter.NullableAnnotation == NullableAnnotation.Annotated ? "?" : string.Empty;
                var optionalValue = parameter.HasExplicitDefaultValue ? $" = {parameter.ExplicitDefaultValue.GetDefaultValue()}" : string.Empty;
                parameters[i + 1] = $"{parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}{nullableAnnotation} {parameter.Name}{optionalValue}";
            }

            StartBlock($"public static {fullyQualifiedDestination} Map{(_mappingContext.LongName ? ($"To{_destination.Name}") : string.Empty)}({string.Join(", ", parameters)})");

            if (!_source.IsValueType)
            {
                WriteIndentedLine("var target = self is null ? throw new ArgumentNullException(nameof(self)) :");
                namespaces.Add(typeof(ArgumentNullException));
                Indent();
            }
            else
            {
                _indentWriter.Write("var target =");
            }

            if (constructor.Parameters.Length == 0)
            {
                StartBlock($"new {fullyQualifiedDestination}()");
            }
            else
            {
                StartBlock(
                    $"new {fullyQualifiedDestination}({string.Join(", ", constructor.Parameters.Select(_ => _.Name))})");
            }

            if (!_source.IsValueType)
            {
                Unindent();
            }
        }

        WriteIndentedLine();

        // Use object initializer syntax if the destination type has a default constructor.
        // Required for 'required' properties.

        var collectionProperties = new List<(IPropertySymbol source, IPropertySymbol destination)>();

        var assignTerminator = constructor != null ? "," : ";";

        var targetPrefix = constructor != null ? string.Empty : "target.";

        foreach (var destinationProperty in _destinationProperties)
        {
            if (_source.GetBaseTypesAndThis().SelectMany(n => n.GetMembers(destinationProperty.Name).OfType<IPropertySymbol>()).SingleOrDefault() is not IPropertySymbol sourceProperty)
            {
                // TODO: diagnostics
                continue;
            }

            if (destinationProperty.HasSetter())
            {
                if (sourceProperty.Type.IsAssignableTo(destinationProperty.Type))
                {
                    WriteIndentedLine($"{targetPrefix}{destinationProperty.Name} = ({destinationProperty.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)})self.{destinationProperty.Name}{assignTerminator}");
                }
                else
                {
                    string? methodName = null;

                    var nullableAnnotation = sourceProperty.NullableAnnotation == NullableAnnotation.Annotated ? "?" : string.Empty;

                    if ((methodName = sourceProperty.GetConversionMethod(destinationProperty)) != null)
                    {
                        WriteIndentedLine($"{targetPrefix}{destinationProperty.Name} = self.{destinationProperty.Name}{nullableAnnotation}.{methodName}(){assignTerminator}");
                    }
                    else if (destinationProperty.Type.TypeKind == TypeKind.Enum)
                    {
                        WriteIndentedLine($"{targetPrefix}{destinationProperty.Name} = self.{destinationProperty.Name}.MapToEnum<{$"global::{destinationProperty.Type.ContainingNamespace.Name}.{destinationProperty.Type.Name}"}>(){assignTerminator}");
                    }
                    else
                    {
                        var (s, t) = _targets.Where(e => e.HasValue).Select(e => e!.Value).Where(e => SymbolEqualityComparer.Default.Equals(sourceProperty.Type, e.source) && SymbolEqualityComparer.Default.Equals(destinationProperty.Type, e.destination)).Select(e => (e.source, e.destination)).FirstOrDefault();
                        if (s != null && t != null)
                        {
                            var nullConditional = sourceProperty.Type.IsReferenceType || sourceProperty.NullableAnnotation == NullableAnnotation.Annotated ? "?" : string.Empty;
                            WriteIndentedLine($"{targetPrefix}{destinationProperty.Name} = self.{destinationProperty.Name}{nullConditional}.Map{(_mappingContext.LongName ? ($"To{destinationProperty.Name}") : string.Empty)}(){assignTerminator}");
                        }
                    }
                }
            }
            else if (sourceProperty.IsEnumerableCollection())
            {
                collectionProperties.Add((sourceProperty, destinationProperty));
            }
            else
            {
                // TODO: diagnostics

                WriteIndentedLine($"// Can't map {sourceProperty.FullyQualifiedName()} to {destinationProperty.FullyQualifiedName()}.");
            }
        }

        if (constructor != null)
        {
            EndBlock(";");
        }

        foreach (var (sourceProperty, destinationProperty) in collectionProperties)
        {
            List<(IPropertySymbol sourceProperty, IPropertySymbol destinationProperty)>? collections = new() { (sourceProperty, destinationProperty) };
            MapCollections(collections, _indentWriter, "target.", string.Empty);
        }

        WriteIndentedLine();
        WriteIndentedLine("return target;");

        EndBlock();
    }

    private void BuildMapToProtobufExtensionMethod(IMethodSymbol constructor, NamespaceGatherer namespaces)
    {
        var fullyQualifiedSource = _source.FullyQualifiedName();
        var fullyQualifiedDestination = _destination.FullyQualifiedName();

        var parameters = new string[constructor.Parameters.Length + 1];
        parameters[0] = $"this {fullyQualifiedSource} self";

        for (var i = 0; i < constructor.Parameters.Length; i++)
        {
            var parameter = constructor.Parameters[i];
            namespaces.Add(parameter.Type.ContainingNamespace);
            var nullableAnnotation = parameter.NullableAnnotation == NullableAnnotation.Annotated ? "?" : string.Empty;
            var optionalValue = parameter.HasExplicitDefaultValue ? $" = {parameter.ExplicitDefaultValue.GetDefaultValue()}" : string.Empty;
            parameters[i + 1] = $"{parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}{nullableAnnotation} {parameter.Name}{optionalValue}";
        }

        StartBlock($"public static {fullyQualifiedDestination} Map{(_mappingContext.LongName ? _destination.Name : string.Empty)}({string.Join(", ", parameters)})");

        if (!_source.IsValueType)
        {
            WriteIndentedLine("var target = self is null");
            Indent();
            WriteIndentedLine("? throw new ArgumentNullException(nameof(self))");
            WriteIndented(": ");
            namespaces.Add(typeof(ArgumentNullException));
        }
        else
        {
            WriteIndentedLine($"var target = ");
        }

        Indent();

        if (constructor != null)
        {
            if (constructor.Parameters.Length == 0)
            {
                WriteIndentedLine($"new {fullyQualifiedDestination}();");
            }
            else
            {
                WriteIndentedLine($"new {fullyQualifiedDestination}({string.Join(", ", constructor.Parameters.Select(_ => _.Name))});");
            }
        }

        if (!_source.IsValueType)
        {
            Unindent();
        }

        WriteIndentedLine();
        Unindent();

        foreach (var destinationProperty in _destinationProperties)
        {
            if (_source.GetBaseTypesAndThis().SelectMany(n => n.GetMembers(destinationProperty.Name).OfType<IPropertySymbol>()).SingleOrDefault() is not IPropertySymbol sourceProperty)
            {
                // TODO: diagnostics
                continue;
            }

            //
            // Set the property only if it's not already set to the Protobuf default.
            // This ensures proper treatment of 'oneof' fields.
            //
            // https://developers.google.com/protocol-buffers/docs/proto3#default
            // https://developers.google.com/protocol-buffers/docs/proto3#oneof
            //

            if (destinationProperty.HasSetter())
            {
                if (sourceProperty.Type.IsAssignableTo(destinationProperty.Type))
                {
                    if (destinationProperty.Type.IsStringType())
                    {
                        StartBlock($"if (!string.IsNullOrEmpty(self.{destinationProperty.Name}))");
                        WriteIndentedLine($"target.{destinationProperty.Name} = self.{destinationProperty.Name};");
                        EndBlock();
                    }
                    else
                    {
                        StartBlock($"if (self.{destinationProperty.Name} != default)");
                        WriteIndentedLine($"target.{destinationProperty.Name} = self.{destinationProperty.Name};");
                        EndBlock();
                    }
                }
                else
                {
                    string? methodName = null;

                    if ((methodName = sourceProperty.GetConversionMethod(destinationProperty)) != null)
                    {
                        StartBlock($"if (self.{destinationProperty.Name} != default)");
                        var nullConditional = sourceProperty.NullableAnnotation == NullableAnnotation.Annotated ? "?" : string.Empty;
                        WriteIndentedLine($"target.{destinationProperty.Name} = self.{destinationProperty.Name}.{methodName}();");
                        EndBlock(Environment.NewLine);
                    }
                    else if (destinationProperty.Type.TypeKind == TypeKind.Enum && sourceProperty.NullableAnnotation != NullableAnnotation.Annotated)
                    {
                        StartBlock($"if (self.{destinationProperty.Name} != default)");
                        WriteIndentedLine($"target.{destinationProperty.Name} = self.{destinationProperty.Name}.MapToEnum<{$"global::{destinationProperty.Type.ContainingNamespace.Name}.{destinationProperty.Type.Name}"}>();");
                        EndBlock(Environment.NewLine);
                    }
                    else if (sourceProperty.Type.IsByteArrayType())
                    {
                        StartBlock($"if (self.{destinationProperty.Name}?.Length > 0)");
                        WriteIndentedLine($"target.{destinationProperty.Name} = self.{destinationProperty.Name}?.MapTo{destinationProperty.Type.Name}();");
                        EndBlock(Environment.NewLine);
                    }
                    else if (sourceProperty.NullableAnnotation == NullableAnnotation.Annotated && _destination.GetMembers($"Has{destinationProperty.Name}").OfType<IPropertySymbol>().SingleOrDefault() != null)
                    {
                        StartBlock($"if (self.{destinationProperty.Name}.HasValue)");
                        WriteIndentedLine($"target.{destinationProperty.Name} = self.{destinationProperty.Name}.Value;");
                        EndBlock(Environment.NewLine);
                    }
                    else
                    {
                        var (s, t) = _targets.Where(e => e.HasValue).Select(e => e!.Value).Where(e => SymbolEqualityComparer.Default.Equals(sourceProperty.Type, e.source) && SymbolEqualityComparer.Default.Equals(destinationProperty.Type, e.destination)).Select(e => (e.source, e.destination)).FirstOrDefault();
                        if (s != null && t != null)
                        {
                            if (sourceProperty.Type.IsReferenceType)
                            {
                                StartBlock($"if (self.{destinationProperty.Name} != default)");
                            }

                            var nullConditional = sourceProperty.Type.IsReferenceType || sourceProperty.NullableAnnotation == NullableAnnotation.Annotated ? "?" : string.Empty;
                            WriteIndentedLine($"target.{destinationProperty.Name} = self.{destinationProperty.Name}{nullConditional}.Map();");

                            if (sourceProperty.Type.IsReferenceType)
                            {
                                EndBlock(Environment.NewLine);
                            }
                        }
                        else
                        {
                            // TODO: diagnostics

                            WriteIndentedLine($"// Can't map {sourceProperty.FullyQualifiedName()} to {destinationProperty.FullyQualifiedName()}.");
                        }
                    }
                }
            }
            else if (sourceProperty.IsEnumerableCollection())
            {
                List<(IPropertySymbol sourceProperty, IPropertySymbol destinationProperty)>? collections = new() { (sourceProperty, destinationProperty) };
                MapCollections(collections, _indentWriter, "target.", string.Empty);
            }
        }

        WriteIndentedLine();
        WriteIndentedLine("return target;");

        EndBlock();
    }

    private void BuildMapFromProtobufExtensionMethod(NamespaceGatherer namespaces, IMethodSymbol? constructor = null)
    {
        var fullyQualifiedSource = _source.FullyQualifiedName();
        var fullyQualifiedDestination = _destination.FullyQualifiedName();

        var parameters = new string[constructor == null ? 1 : constructor.Parameters.Length + 1];
        parameters[0] = $"this {fullyQualifiedSource} self";

        if (constructor == null)
        {
            WriteIndentedLine($"public static {fullyQualifiedDestination} Map{(_mappingContext.LongName ? ($"To{_destination.Name}") : string.Empty)}(this {fullyQualifiedSource} self, {fullyQualifiedDestination} target)");
        }
        else
        {
            for (var i = 0; i < constructor.Parameters.Length; i++)
            {
                var parameter = constructor.Parameters[i];

                if (parameter.Type.ContainingNamespace != null)
                {
                    namespaces.Add(parameter.Type.ContainingNamespace);
                }

                var nullableAnnotation = parameter.NullableAnnotation == NullableAnnotation.Annotated ? "?" : string.Empty;
                var optionalValue = parameter.HasExplicitDefaultValue ? $" = {parameter.ExplicitDefaultValue.GetDefaultValue()}" : string.Empty;
                parameters[i + 1] = $"{parameter.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}{nullableAnnotation} {parameter.Name}{optionalValue}";
            }

            WriteIndentedLine($"public static {fullyQualifiedDestination} Map{(_mappingContext.LongName ? ($"To{_destination.Name}") : string.Empty)}({string.Join(", ", parameters)})");
        }

        WriteIndentedLine("{");
        Indent();

        if (!_source.IsValueType)
        {
            if (constructor != null)
            {
                WriteIndentedLine("var target = self is null");
                Indent();
                WriteIndentedLine("? throw new ArgumentNullException(nameof(self))");
            }

            namespaces.Add(typeof(ArgumentNullException));
        }
        else
        {
            WriteIndentedLine($"if (target == null) throw new ArgumentNullException(nameof(target));{Environment.NewLine}");
        }

        if (constructor != null)
        {
            if (constructor.Parameters.Length == 0)
            {
                WriteIndentedLine($": new {fullyQualifiedDestination}()");
            }
            else
            {
                WriteIndentedLine($": new {fullyQualifiedDestination}({string.Join(", ", constructor.Parameters.Select(_ => _.Name))})");
            }

            Indent();
            WriteIndentedLine("{");
            Indent();
        }

        List<(IPropertySymbol sourceProperty, IPropertySymbol destinationProperty)> optionals = new();
        List<(IPropertySymbol sourceProperty, IPropertySymbol destinationProperty)> collections = new();

        foreach (var destinationProperty in _destinationProperties)
        {
            if (_source.GetMembers(destinationProperty.Name).OfType<IPropertySymbol>().SingleOrDefault() is not IPropertySymbol sourceProperty)
            {
                // TODO: diagnostics
                continue;
            }

            if (_source.GetMembers($"Has{destinationProperty.Name}").OfType<IPropertySymbol>().SingleOrDefault() != null && destinationProperty.HasSetter())
            {
                optionals.Add((sourceProperty, destinationProperty));
            }
            else if (sourceProperty.IsEnumerableCollection() && destinationProperty.IsMutableCollection())
            {
                // Protobuf source is a collection that's not a string and we're not mapping it to a byte array
                collections.Add((sourceProperty, destinationProperty));
            }
            else
            {
                if (constructor != null)
                {
                    WritePropertyMapping(sourceProperty, destinationProperty, _indentWriter, string.Empty, $",{Environment.NewLine}");
                }
                else
                {
                    WritePropertyMapping(sourceProperty, destinationProperty, _indentWriter, "target.", $";{Environment.NewLine}");
                }
            }
        }

        if (constructor != null)
        {
            EndBlock($";{Environment.NewLine}");
            Unindent();
            Unindent();
        }

        foreach (var (sourceProperty, destinationProperty) in optionals)
        {
            StartBlock($"if (self.Has{destinationProperty.Name})");

            WritePropertyMapping(sourceProperty, destinationProperty, _indentWriter, "target.", $";");

            EndBlock(Environment.NewLine);
        }

        MapCollections(collections, _indentWriter, "target.", string.Empty);

        WriteIndentedLine("return target;");

        EndBlock(Environment.NewLine);
    }

    private void WritePropertyMapping(IPropertySymbol sourceProperty, IPropertySymbol destinationProperty, IndentedTextWriter _indentWriter, string prefix, string postfix)
    {
        string? methodName;

        if (sourceProperty.IsEnumerableCollection() && destinationProperty.IsMutableCollection())
        {
            List<(IPropertySymbol sourceProperty, IPropertySymbol destinationProperty)>? collections = new() { (sourceProperty, destinationProperty) };
            MapCollections(collections, _indentWriter, "target.", string.Empty);
        }
        else if (destinationProperty.HasSetter())
        {
            var nullConditional
                = (destinationProperty.Type.IsReferenceType && sourceProperty.Type.IsReferenceType)
                || sourceProperty.NullableAnnotation == NullableAnnotation.Annotated
                ? "?" : string.Empty;

            if (sourceProperty.Type.IsAssignableTo(destinationProperty.Type))
            {
                WriteIndentedLine($"{prefix}{destinationProperty.Name} = self.{destinationProperty.Name}{postfix}");
            }
            else if ((methodName = sourceProperty.GetConversionMethod(destinationProperty)) != null)
            {
                WriteIndentedLine($"{prefix}{destinationProperty.Name} = self.{destinationProperty.Name}.{methodName}(){postfix}");
            }
            else if (destinationProperty.Type.TypeKind == TypeKind.Enum)
            {
                WriteIndentedLine($"{prefix}{destinationProperty.Name} = self.{destinationProperty.Name}.MapToEnum<{$"global::{destinationProperty.Type.ContainingNamespace.Name}.{destinationProperty.Type.Name}"}>(){postfix}");
            }
            else if (!sourceProperty.IsEnumerableCollection())
            {
                var (s, t) = _targets.Where(e => e.HasValue).Select(e => e!.Value).Where(e => SymbolEqualityComparer.Default.Equals(sourceProperty.Type, e.source) && SymbolEqualityComparer.Default.Equals(destinationProperty.Type, e.destination)).Select(e => (e.source, e.destination)).FirstOrDefault();
                if (s != null && t != null)
                {
                    WriteIndentedLine($"{prefix}{destinationProperty.Name} = self.{destinationProperty.Name}{nullConditional}.Map(){postfix}");
                }
                else
                {
                    // TODO: diagnostics

                    WriteIndentedLine($"// Can't map {sourceProperty.FullyQualifiedName()} to {destinationProperty.FullyQualifiedName()}.");
                }
            }
            else
            {
                // TODO: diagnostics

                WriteIndentedLine($"// Can't map {sourceProperty.FullyQualifiedName()} to {destinationProperty.FullyQualifiedName()}.");
            }
        }
        else
        {
            // TODO: diagnostics

            WriteIndentedLine($"// Can't map {sourceProperty.FullyQualifiedName()} to {destinationProperty.FullyQualifiedName()}.");
        }
    }

    private void MapCollections(List<(IPropertySymbol sourceProperty, IPropertySymbol destinationProperty)> collections, IndentedTextWriter _indentWriter, string prefix, string postfix)
    {
        foreach (var (sourceProperty, destinationProperty) in collections)
        {
            if (sourceProperty.IsEnumerableCollection() && destinationProperty.IsMutableCollection())
            {
                var sourceType = sourceProperty.GetCollectionType();
                var destinationType = destinationProperty.GetCollectionType();

                if (sourceType != null && destinationType != null)
                {
                    WriteCollectionElementMapping(sourceProperty, destinationProperty, sourceType, destinationType, _indentWriter, prefix, postfix);
                }
            }
            else
            {
                // TODO: diagnostics

                WriteIndentedLine($"// Can't map {sourceProperty.FullyQualifiedName()} to {destinationProperty.FullyQualifiedName()}.");
            }
        }
    }

    private void WriteCollectionElementMapping(IPropertySymbol sourceProperty, IPropertySymbol destinationProperty, ITypeSymbol sourceCollectionTypeSymbol, ITypeSymbol destinationCollectionTypeSymbol, IndentedTextWriter _indentWriter, string prefix, string postfix)
    {
        string? methodName;

        if (_compilation.ClassifyCommonConversion(sourceCollectionTypeSymbol, destinationCollectionTypeSymbol).IsImplicit)
        {
            StartBlock($"foreach(var e in self.{sourceProperty.Name})");
            WriteIndentedLine($"{prefix}{destinationProperty.Name}.Add(e);");
            EndBlock(Environment.NewLine);
        }
        else if ((methodName = sourceCollectionTypeSymbol.GetConversionMethod(destinationCollectionTypeSymbol)) != null)
        {
            StartBlock($"foreach(var e in self.{sourceProperty.Name})");
            WriteIndentedLine($"{prefix}{destinationProperty.Name}.Add(e.{methodName}());");
            EndBlock(Environment.NewLine);
        }
        else if (destinationCollectionTypeSymbol.TypeKind == TypeKind.Enum)
        {
            StartBlock($"foreach(var e in self.{sourceProperty.Name})");
            var ss = $"{prefix}{destinationProperty.Name}.Add(e.MapToEnum<{$"global::{destinationProperty.ContainingNamespace.ToDisplayString()}.{destinationCollectionTypeSymbol.Name}"}>());";
            WriteIndentedLine($"{prefix}{destinationProperty.Name}.Add(e.MapToEnum<{$"global::{destinationProperty.ContainingNamespace.ToDisplayString()}.{destinationCollectionTypeSymbol.Name}"}>());");
            EndBlock(Environment.NewLine);
        }
        else
        {
            var (s, t) = _targets.Where(e => e.HasValue).Select(e => e!.Value).Where(e => SymbolEqualityComparer.Default.Equals(sourceCollectionTypeSymbol, e.source) && SymbolEqualityComparer.Default.Equals(destinationCollectionTypeSymbol, e.destination)).Select(e => (e.source, e.destination)).FirstOrDefault();
            if (s != null && t != null && HasDefaultConstructor(t))
            {
                var imessage = _compilation.GetTypeByMetadataName("Google.Protobuf.IMessage");
                var isProtobufSource = imessage != null && _compilation.ClassifyCommonConversion(s, imessage).IsImplicit;
                var isProtobufTarget = imessage != null && _compilation.ClassifyCommonConversion(t, imessage).IsImplicit;
                StartBlock($"foreach(var e in self.{sourceProperty.Name})");
                WriteIndentedLine($"{prefix}{destinationProperty.Name}.Add(e.Map());");
                EndBlock(Environment.NewLine);
            }
            else
            {
                // TODO: diagnostics

                WriteIndentedLine($"// Can't map {sourceProperty.FullyQualifiedName()} to {destinationProperty.FullyQualifiedName()}.");
            }
        }
    }

    private bool HasDefaultConstructor(INamedTypeSymbol type)
    {
        return type.InstanceConstructors.Any(_ => _.DeclaredAccessibility == Accessibility.Public && _.Parameters.Length == 0);
    }

    private void StartBlock(string what, [CallerFilePath] string file = "", [CallerMemberName] string member = "", [CallerLineNumber] int line = 0)
    {
        WriteIndentedLine(what, file, member, line);
        WriteIndentedLine("{", file, member, line);
        Indent(file, member, line);
    }

    private void EndBlock(string what = "", [CallerFilePath] string file = "", [CallerMemberName] string member = "", [CallerLineNumber] int line = 0)
    {
        Unindent(file, member, line);
        WriteIndentedLine($"}}{what}", file, member, line);
    }

    private void WriteIndented(string what = "", [CallerFilePath] string file = "", [CallerMemberName] string member = "", [CallerLineNumber] int line = 0)
    {
        DebugLine(string.Empty, file, member, line);
        _indentWriter.Write(what);
    }

    private void WriteIndentedLine(string what = "", [CallerFilePath] string file = "", [CallerMemberName] string member = "", [CallerLineNumber] int line = 0)
    {
        DebugLine(string.Empty, file, member, line);
        _indentWriter.WriteLine(what);
    }

    private void Indent([CallerFilePath] string file = "", [CallerMemberName] string member = "", [CallerLineNumber] int line = 0)
    {
        DebugLine(">>>", file, member, line);
        _indentWriter.Indent++;
    }

    private void Unindent([CallerFilePath] string file = "", [CallerMemberName] string member = "", [CallerLineNumber] int line = 0)
    {
        DebugLine("<<<", file, member, line);
        _indentWriter.Indent--;
    }

    [Conditional("_DEBUG")]
    private void DebugLine(string what = "", [CallerFilePath] string file = "", [CallerMemberName] string member = "", [CallerLineNumber] int line = 0)
        => _indentWriter.WriteLine($"// {what}{(string.IsNullOrWhiteSpace(what) ? string.Empty : ($"{what}:"))}{file}:{member}:{line}");

    public void Dispose()
    {
        _indentWriter.Dispose();
        _writer.Dispose();
    }
}
